// This Arduino code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = ESP32-CYD
// Board = ESP32-WROOM-32
// Backend = arduino

#include <SPI.h>
#include <string.h>
typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int32_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
// typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint32_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  4000000

#define SERIAL_BEGIN(BAUD_RATE)     Serial.begin(BAUD_RATE)
#define SERIAL_WRITE(CHARACTER)     Serial.write(CHARACTER) 
#define SERIAL_READ()               Serial.read()
#define SERIAL_PRINT(MESSAGE)       Serial.print(MESSAGE)
#define SERIAL_PRINTLN(MESSAGE)     Serial.println(MESSAGE)
#define SERIAL_AVAILABLE()          Serial.available()    

// Project name: Aixt, https://github.com/fermarsan/aixt.git
// Authors:
//		- Jahn Delgado
//		- Fernando M. Santa
// Date: 02/04/2025
// License: MIT
//
// Description: Example of a Library module.
//

// #undef ILI9341_DRIVER
// #define ILI9341_2_DRIVER

// #define TFT_WIDTH  240
// #define TFT_HEIGHT 320

// #define TFT_BL   21
// #define TFT_BACKLIGHT_ON HIGH

// #undef TFT_MISO
// #undef TFT_MOSI
// #undef TFT_SCLK
// #undef TFT_CS
// #undef TFT_DC
// #undef TFT_RST

// #define TFT_MISO 12
// #define TFT_MOSI 13
// #define TFT_SCLK 14
// #define TFT_CS   15  // Chip select control pin
// #define TFT_DC    2  // Data Command control pin
// #define TFT_RST  -1  // Set TFT_RST to -1 if display RESET is connected to ESP32 board RST
// #define TOUCH_CS 33     // Chip select pin (T_CS) of touch screen

// #undef SPI_FREQUENCY
// #define SPI_FREQUENCY  55000000

// #define USE_HSPI_PORT
//
//

#include "./TFT_eSPI.h"

#define TFT_FILLSCREEN(COLOR)   tft.fillScreen(COLOR)
#define TFT_SETTEXTCOLOR(COLOR, BKG_COLOR)  tft.setTextColor(COLOR, BKG_COLOR)
#define TFT_SETROTATION(ANGLE)  tft.setRotation(ANGLE)
#define TFT_INIT()  tft.init()
#define TFT_DRAWCENTRESTRING(TEMPTEXT, CENTERX, TEXTY, FONT_ZISE)  tft.drawCentreString(TEMPTEXT, CENTERX, TEXTY, FONT_ZISE)

TFT_eSPI tft = TFT_eSPI();

void  main__print_touch_to_display(i32 touch_x, i32 touch_y, i32 touch_z);

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

const i32 _const_pin__gpio0 = (i32)(0);
const i32 _const_pin__gpio1 = (i32)(1);
const i32 _const_pin__gpio2 = (i32)(2);
const i32 _const_pin__gpio3 = (i32)(3);
const i32 _const_pin__gpio4 = (i32)(4);
const i32 _const_pin__gpio5 = (i32)(5);
const i32 _const_pin__gpio6 = (i32)(6);
const i32 _const_pin__gpio7 = (i32)(7);
const i32 _const_pin__gpio8 = (i32)(8);
const i32 _const_pin__gpio9 = (i32)(9);
const i32 _const_pin__gpio10 = (i32)(10);
const i32 _const_pin__gpio11 = (i32)(11);
const i32 _const_pin__gpio12 = (i32)(12);
const i32 _const_pin__gpio13 = (i32)(13);
const i32 _const_pin__gpio14 = (i32)(14);
const i32 _const_pin__gpio15 = (i32)(15);
const i32 _const_pin__gpio16 = (i32)(16);
const i32 _const_pin__gpio17 = (i32)(17);
const i32 _const_pin__gpio18 = (i32)(18);
const i32 _const_pin__gpio19 = (i32)(19);
const i32 _const_pin__gpio20 = (i32)(20);
const i32 _const_pin__gpio21 = (i32)(21);
const i32 _const_pin__gpio22 = (i32)(22);
const i32 _const_pin__gpio23 = (i32)(23);
const i32 _const_pin__gpio24 = (i32)(24);
const i32 _const_pin__gpio25 = (i32)(25);
const i32 _const_pin__gpio26 = (i32)(26);
const i32 _const_pin__gpio27 = (i32)(27);
const i32 _const_pin__gpio28 = (i32)(28);
const i32 _const_pin__gpio29 = (i32)(29);
const i32 _const_pin__gpio30 = (i32)(30);
const i32 _const_pin__gpio31 = (i32)(31);
const i32 _const_pin__gpio32 = (i32)(32);
const i32 _const_pin__gpio33 = (i32)(33);
const i32 _const_pin__gpio34 = (i32)(34);
const i32 _const_pin__gpio35 = (i32)(35);
const i32 _const_pin__gpio36 = (i32)(36);
const i32 _const_pin__gpio39 = (i32)(39);
const u8 _const_pin__input = (u8)(INPUT);
const u8 _const_pin__output = (u8)(OUTPUT);
const u8 _const_pin__in_pullup = (u8)(INPUT_PULLUP);

#define pin__read(name)  digitalRead(name)

#define pin__low(name) digitalWrite(name, LOW)

#define pin__write(name, val) digitalWrite(name, val)

#define pin__setup(name, mode) pinMode(name, mode)

#define pin__high(name) digitalWrite(name, HIGH)

#define uart__read()  SERIAL_READ()

#define uart__any()  SERIAL_AVAILABLE()

#define uart__println(message) SERIAL_PRINTLN(message)

#define uart__write(character) SERIAL_WRITE(character)

#define uart__print(message) SERIAL_PRINT(message)

#define uart__setup(baud_rate) SERIAL_BEGIN(baud_rate)

#define _const_tft_espi__white TFT_WHITE
#define _const_tft_espi__black TFT_BLACK
#define _const_tft_espi__temp_text TFT_TEMP_TEXT
#define _const_tft_espi__center_x TFT_CENTER_X
#define _const_tft_espi__text_y TFT_TEXT_Y
#define _const_tft_espi__font_size TFT_FONT_SIZE

#define tft_espi__fill_screen(color) TFT_FILLSCREEN(color)

#define tft_espi__set_rotation(angle) TFT_SETROTATION(angle)

#define tft_espi__setup() TFT_INIT()

#define tft_espi__draw_centre_string(temp_text, center_x, text_y, font_size) TFT_DRAWCENTRESTRING(temp_text, center_x, text_y, font_size)

#define tft_espi__set_text_color(color, bkg_color) TFT_SETTEXTCOLOR(color, bkg_color)

const i32 _const_main__screen_width = (i32)(320);
const i32 _const_main__screen_height = (i32)(240);
const i32 _const_main__font_size = (i32)(2);

 void  main__print_touch_to_display(i32 touch_x, i32 touch_y, i32 touch_z) {
	tft_espi__fill_screen(_const_tft_espi__white); 
	tft_espi__set_text_color(_const_tft_espi__black, _const_tft_espi__white); 
	i32 center_x = (i32)(_const_main__screen_width / 2); 
	i32 text_y = (i32)(80); 
	char temp_text[50]; 
	strcpy(temp_text, "Hola Mundo"); 
	tft_espi__draw_centre_string(temp_text, center_x, text_y, _const_main__font_size); 
}

 void setup() {
	i32 x = (i32)(0);
	i32 y = (i32)(0);
	i32 z = (i32)(0); 
	uart__setup(115200); 
	tft_espi__setup(); 
	tft_espi__set_rotation(1); 
	tft_espi__fill_screen(_const_tft_espi__white); 
	tft_espi__set_text_color(_const_tft_espi__black, _const_tft_espi__white); 
	while( true ) {
		main__print_touch_to_display(x, y, z); 
		time__sleep_ms(100); 
	} 
}

void loop(){
}
