// This Arduino code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = Arduino-Nano
// Board = Arduino Nano
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
// typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint8_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  16000000

// #if defined(EXT_IRQ_IN_USE) || defined(TIMER0_IRQ_IN_USE)  // if any interrupt source is activated

// #endif  // defined(EXT_IRQ_IN_USE)  ||  defined(TIMER0_IRQ_IN_USE)
i32  random__in_range(i32 min, i32 max);
i32  random__rand(i32 max);

#define RANDOMINRANGE(min, max)     random(min, max)

void  random__seed(u32 s);

#define _const_port__b 0
#define _const_port__c 1
#define _const_port__d 2
#define _const_port__all_inputs 0b11111111
#define _const_port__all_outputs 0b00000000

#define port__read(name)  (u8)(*(&PINB + (name * 3)))

#define port__setup(name, mode) *(&DDRB + (name * 3)) = ~mode

#define port__write(name, value) *(&PORTB + (name * 3)) = value

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

inline i32  random__in_range(i32 min, i32 max) {
	return RANDOMINRANGE(min, max); 
}

inline i32  random__rand(i32 max) {
	return random(max); 
}

inline void  random__seed(u32 s) {
	randomSeed(s); 
}

#define _const_main__led_0 13

 void setup() {
	port__setup(_const_port__b, _const_port__all_outputs); 
	port__write(_const_port__b, (u8)(random__in_range(0, 255))); 
	time__sleep_ms(500); 
}

void loop(){
}
