// This Arduino code was automatically generated by Aixt Project
//     https://github.com/fermarsan/aixt
// Device = Arduino-Uno
// Board = Arduino Uno
// Backend = arduino

typedef int8_t i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int8_t isize;
typedef int32_t int_literal;
typedef uint8_t u8;
// typedef uint16_t u16;
typedef uint32_t u32;
typedef uint64_t u64;
typedef uint8_t usize;
typedef float f32;
typedef double f64;
typedef double float_literal;
typedef char rune;

#define _const_main__cpu_freq_mhz	_const_main__cpu_freq/1000000
#define _const_main__cpu_freq  16000000

#ifdef SPI_IRQ_IN_USE    
void (*ptr_spi_isr)(void);      // Interrupt Service Routine pointer

ISR (SPI_STC_vect) {
	ptr_spi_isr();
	//   Slavereceived = SPDR;         
	//   received = true;                        
}
#endif  // SPI_IRQ_IN_USE 

#include "DigitShield_A2.h"

#define DIGITSHIELD_BEGIN()                     DigitShield.begin()
#define DIGITSHIELD_SETVALUE(P1)                DigitShield.setValue((int)P1)
#define DIGITSHIELD_SETVALUEFLOAT(P1)           DigitShield.setValue((double)P1)
#define DIGITSHIELD_SETPRECISION(P1)            DigitShield.setPrecision(P1)
#define DIGITSHIELD_SETLEADINGZEROS(P1)         DigitShield.setLeadingZeros(P1)
#define DIGITSHIELD_SETBLANK(P1)                DigitShield.setBlank(P1)
#define DIGITSHIELD_SETDIGIT(P1, P2)            DigitShield.setDigit(P1, P2)
#define DIGITSHIELD_SETDECIMALPOINT(P1, P2)     DigitShield.setDecimalPoint(P1, P2)

#define _const_main__led_0 13

#define disp7seg__leading_zeros(p1) DIGITSHIELD_SETLEADINGZEROS(p1)

#define disp7seg__write(p1) DIGITSHIELD_SETVALUE(p1)

#define disp7seg__setup() DIGITSHIELD_BEGIN()

#define disp7seg__digit(p1, p2) DIGITSHIELD_SETDIGIT(p1, p2)

#define disp7seg__precision(p1) DIGITSHIELD_SETPRECISION(p1)

#define disp7seg__decimal_point(p1, p2) DIGITSHIELD_SETDECIMALPOINT(p1, p2)

#define disp7seg__blank(p1) DIGITSHIELD_SETBLANK(p1)

#define time__sleep(ts) delay(ts * 1000)

#define time__sleep_ms(tms) delay(tms)

#define time__sleep_us(tus) delayMicroseconds(tus)

 void setup() {
	disp7seg__setup(); 
	i32 cont = (i32)(0); 
	while( true ) {
		disp7seg__write(cont); 
		cont++; 
		time__sleep_ms(500); 
	} 
}

void loop(){
}
